### ISSUE TITLE
Contructor erros when upgraded the complete angular to 5.2.3

### ISSUE THREAD

**Issue by V2NileshSukalikar** [sketch7/angular-skeleton-app#1]
ERROR in src/app/areas/nav/nav.component.ts(27,21): error TS2564: Property 'menuElementRef' has no initializer and is not definitely assigned in the constructor.
src/app/areas/nav/nav.component.ts(29,10): error TS2564: Property 'domClickListener$$' has no initializer and is not definitely assigned in the constructor.
src/app/areas/projects/project.component.ts(11,11): error TS2564: Property 'project' has no initializer and is not definitely assigned in the constructor.

**Comment by stephenlautier** [comment]
When I have some time I will try to update it and see if I manage to get it working. Thanks

**Comment by V2NileshSukalikar** [comment]
Hi , i have solved above errors. I have upgraded complete package.json files now as per required dependencies version. Compiler CLI was expecting other version of typescipt and are not suported with higher version of typescript which why it was giving an error. If you want i can share upgraded package.json file with you with compitable dependices and all.

Also, can you please check your testing framework. Its not working properly and giving an error. Tetsing cases are failing. It was not even working with your version of packge.json. It is important for me . Can you please check.

**Comment by stephenlautier** [comment]
Thanks for the issue. I had updated most of the packages to latest, fixed tests and added some more improvements.

To see exactly what was changed see [changes](https://github.com/sketch7/angular-skeleton-app/compare/1.0.0...1.0.1) and/or [changelog](https://github.com/sketch7/angular-skeleton-app/blob/master/CHANGELOG.md)
